theme = "kanagawa"

[editor]
bufferline = "always"
cursorline = true
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[keys.normal.g]
x = ":buffer-close"

[keys.normal.space]
t = { d = ":theme kanagawa", l = ":theme catppuccin_latte" }
