alias dc "docker compose"
alias ds "sudo service docker start"
alias gbdd 'git branch -vv | grep \': gone\' | grep -v \'\*\' | awk \'{print $1}\' | xargs -r git branch -d'
alias gl "git log --all --decorate --oneline --graph"
alias gp "git push -u origin HEAD"
alias gs "git status -sb"
alias gui-sw "git update-index --skip-worktree"
alias gui-nsw "git update-index --no-skip-worktree"
alias gw "git worktree"
alias gwa "gw add --guess-remote"
alias gwl "gw list"
alias gwr "gw remove"
alias lg "lazygit"
alias nb "npm run build"
alias nbd "npm run build:docker"
alias ncu "npx -p npm-check-updates@latest ncu --format group"
alias no "npm outdated"
alias nog "no -g"
alias ni "npm i"
alias nig "npm i -g"
alias nr "npm run"
alias ns "npm start"
alias nt "npm test"
alias nu "npm update"
alias nug "nu -g"
alias nv "neovide"
alias t 'tmux new -s (basename "$PWD")'
alias ta "tmux a"
alias v "nvim"
alias vh "nvim --headless --listen localhost:6666"
